# Site setings
name: 'Srikanth Ethiraj'
description: 'Simplifying complexity. Scaling innovation.'
meta_description: 'Empowering engineering teams with automated, secure, and scalable systems.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Empowering engineering teams with automated, secure, and scalable systems."
favicon: 'assets/images/initials.png'
baseurl: 
production_url: https://blog.srikanthethiraj.com/
disqus: 'justgoodthemes'
mailchimp_url: 'https://srikanthethiraj.us19.list-manage.com/subscribe/post?u=42acdd8bd6be3355d0c6df855&amp;id=72ab533508&amp;f_id=00c336e3f0'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: srikanth.ethiraj@gmail.com
#contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'srikanthethiraj'
#facebook: 'username'
github: 'srikantheee84'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
instagram: 'srikanthethiraj'
pinterest: 'srikanthethiraj'
linkedin: 'srikanthethiraj'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  # - text: Style Guide
  #   url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
